name: google_maps_directions
description: Calculate distances, durations & Get shortest route/leg between two points.
version: 0.0.2
homepage: https://github.com/bienvenuelisis/google_maps_directions

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5

dev_dependencies:
  test: any